name: huhu
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
     - images/OIP.jpeg


  fonts:
    - family: Source Code Pro
      fonts:
         - asset: fonts/SourceCodePro-Regular.ttf

    - family: Lilita One
      fonts:
        - asset: fonts/LilitaOne-Regular.ttf

    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Titan
      fonts:
        - asset: fonts/TitanOne-Regular.ttf